<script src="https://cdn.jsdelivr.net/npm/pusher-js@8.4.0/dist/web/pusher.min.js"></script>
@include('partials.monitor-page')
@include('partials.last-updated')
@include('partials.detail-realtime-sync')
@include('partials.detail-image-realtime-fix')
@include('partials.detail-media-fix')
@include('partials.detail-empty-media-fix')
@include('partials.map-fallback')
@include('partials.company-brand-fix')
@include('partials.map-height-fix')
@include('partials.detail-rich-text-fix')
