<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit {{ $project->name }} — Tazaka Elektrik Mandiri</title><link rel="icon" type="image/png" href="https://tazaka.co.id/assets/logo-tazaka-PPqkEZXu.png">
    <style>*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#eef2ff;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.wrap{max-width:900px;margin:auto;padding:32px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.brand{display:flex;align-items:center;gap:14px}.brand-logo{width:50px;height:50px;object-fit:contain;border-radius:11px;background:#fff;padding:5px}.brand-name{font-size:13px;font-weight:800;color:#e2e8f0}.eyebrow{color:#7dd3fc;font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.title{font-size:30px;font-weight:800;margin:5px 0}.muted{color:#94a3b8}.card{background:#111827;border:1px solid #1f2937;border-radius:18px;padding:24px;box-shadow:0 18px 50px #0003}.btn{display:inline-block;border:0;border-radius:10px;padding:11px 16px;background:#1e293b;color:#fff;cursor:pointer;font-weight:700;text-decoration:none}.btn.primary{background:#2563eb}.actions{display:flex;gap:10px;justify-content:flex-end;margin-top:22px}.row,.coords{display:grid;grid-template-columns:1fr 1fr;gap:12px}.section{border-top:1px solid #1f2937;padding-top:17px;margin-top:17px}.section-title{font-size:12px;color:#7dd3fc;font-weight:800;text-transform:uppercase;letter-spacing:.08em;margin-bottom:12px}.progress-box{background:#0b1222;border:1px solid #1f2937;border-radius:14px;padding:16px;margin:14px 0}.progress-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.progress-value{font-size:22px;font-weight:800;color:#7dd3fc}.slider{width:100%;height:8px;appearance:none;-webkit-appearance:none;border-radius:99px;background:linear-gradient(to right,#38bdf8 0%,#38bdf8 var(--progress),#1e293b var(--progress),#1e293b 100%);outline:none;cursor:pointer}.slider::-webkit-slider-thumb{appearance:none;-webkit-appearance:none;width:21px;height:21px;border-radius:50%;background:#fff;border:3px solid #38bdf8}.slider::-moz-range-thumb{width:15px;height:15px;border-radius:50%;background:#fff;border:3px solid #38bdf8}@media(max-width:600px){.wrap{padding:18px}.top{align-items:flex-start;gap:12px;flex-direction:column}.row,.coords{grid-template-columns:1fr}.brand-logo{width:44px;height:44px}}
    </style>
</head>
<body><div class="wrap">
<div class="top"><div class="brand"><img class="brand-logo" src="https://tazaka.co.id/assets/logo-tazaka-PPqkEZXu.png" alt="Logo Tazaka"><div><div class="brand-name">Tazaka Elektrik Mandiri</div><div class="eyebrow">Project Management</div><div class="title">Edit Project</div><div class="muted">{{ $project->name }} · {{ $project->client }}</div></div></div><a class="btn" href="{{ route('admin.projects.show',$project) }}">← Detail</a></div>
<div class="card"><form method="POST" action="{{ route('admin.projects.update',$project) }}">@csrf @method('PUT')
<x-forms.input label="Nama Project" name="name" value="{{ old('name',$project->name) }}" required /><x-forms.input label="Client" name="client" value="{{ old('client',$project->client) }}" required />
<div class="row"><x-forms.select label="Project Type" name="project_type" required><option value="tazaka_order" @selected(old('project_type',$project->project_type)==='tazaka_order')>Tazaka Order</option><option value="subcontract" @selected(old('project_type',$project->project_type)==='subcontract')>Subcontract</option><option value="external" @selected(old('project_type',$project->project_type)==='external')>External</option></x-forms.select><x-forms.input label="Target Completion" name="target_completion_date" type="date" value="{{ old('target_completion_date',$project->target_completion_date?->format('Y-m-d')) }}" /></div>
<x-forms.input label="Project Month" name="project_month" type="month" value="{{ old('project_month',$project->project_month?->format('Y-m')) }}" />
<div class="progress-box"><div class="progress-head"><span class="section-title" style="margin:0">Progress</span><span class="progress-value" id="progressValue">{{ old('progress',$project->progress) }}%</span></div><input class="slider" id="progressSlider" type="range" name="progress" min="0" max="100" step="1" value="{{ old('progress',$project->progress) }}" style="--progress:{{ old('progress',$project->progress) }}%"></div>
<div class="section"><div class="section-title">Project Detail</div><x-forms.textarea label="Description" name="description" placeholder="Tulis deskripsi project...">{{ old('description',$project->description) }}</x-forms.textarea><x-forms.textarea label="Notes" name="notes" placeholder="Tulis catatan project...">{{ old('notes',$project->notes) }}</x-forms.textarea></div>
<div class="section"><div class="section-title">Location</div><x-forms.input label="Location" name="location" value="{{ old('location',$project->location) }}" /><div class="coords"><x-forms.input label="Latitude" name="lat" type="number" step="any" min="-90" max="90" value="{{ old('lat',data_get($project->latlong,'lat')) }}" /><x-forms.input label="Longitude" name="lng" type="number" step="any" min="-180" max="180" value="{{ old('lng',data_get($project->latlong,'lng')) }}" /></div></div>
<div class="actions"><a class="btn" href="{{ route('admin.projects.show',$project) }}">Batal</a><button class="btn primary" type="submit">Simpan Perubahan</button></div></form></div></div>
<script>const slider=document.getElementById('progressSlider'),value=document.getElementById('progressValue');slider?.addEventListener('input',()=>{value.textContent=slider.value+'%';slider.style.setProperty('--progress',slider.value+'%')});</script>
</body></html>
