<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $project->name }} — Tazaka Elektrik Mandiri</title><link rel="icon" type="image/png" href="https://tazaka.co.id/assets/logo-tazaka-PPqkEZXu.png"><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#eef2ff;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.wrap{max-width:950px;margin:auto;padding:32px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:20px;margin-bottom:24px}.brand{display:flex;align-items:center;gap:14px}.brand-logo{width:50px;height:50px;object-fit:contain;border-radius:11px;background:#fff;padding:5px}.brand-name{font-size:13px;font-weight:800;color:#e2e8f0}.eyebrow{color:#7dd3fc;font-size:12px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.title{font-size:30px;font-weight:800;margin:5px 0}.muted{color:#94a3b8}.actions{display:flex;gap:10px}.btn{display:inline-block;border:0;border-radius:10px;padding:11px 16px;background:#1e293b;color:#fff;cursor:pointer;font-weight:700;text-decoration:none}.btn.primary{background:#2563eb}.btn.danger{background:#7f1d1d}.card{background:#111827;border:1px solid #1f2937;border-radius:18px;padding:24px;box-shadow:0 18px 50px #0003}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.item{background:#0b1222;border:1px solid #1f2937;border-radius:12px;padding:15px}.label{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:.08em;font-weight:800}.value{font-size:15px;color:#e2e8f0;margin-top:6px;white-space:pre-wrap}.progress{margin:20px 0}.progress-head{display:flex;justify-content:space-between;margin-bottom:8px}.progress-value{font-size:22px;font-weight:800;color:#7dd3fc}.bar{height:9px;border-radius:99px;background:#1e293b;overflow:hidden}.fill{height:100%;background:#38bdf8;border-radius:99px}.wide{margin-top:12px}.bottom{display:flex;justify-content:space-between;gap:10px;margin-top:22px}.delete-form{margin:0}@media(max-width:600px){.wrap{padding:18px}.top{flex-direction:column}.grid{grid-template-columns:1fr}.bottom{flex-direction:column}.actions{width:100%}.actions .btn{flex:1;text-align:center}.brand-logo{width:44px;height:44px}}
</style></head>
<body><div class="wrap">
<div class="top"><div class="brand"><img class="brand-logo" src="https://tazaka.co.id/assets/logo-tazaka-PPqkEZXu.png" alt="Logo Tazaka"><div><div class="brand-name">Tazaka Elektrik Mandiri</div><div class="eyebrow">Project Detail</div><div class="title">{{ $project->name }}</div><div class="muted">{{ $project->client }}</div></div></div><div class="actions"><a class="btn" href="{{ route('admin.projects.index') }}">← Kembali</a><a class="btn primary" href="{{ route('admin.projects.edit',$project) }}">Edit Project</a></div></div>
<div class="card"><div class="grid"><div class="item"><div class="label">Project Type</div><div class="value">{{ str_replace('_',' ',ucfirst($project->project_type)) }}</div></div><div class="item"><div class="label">Progress</div><div class="value">{{ $project->progress }}%</div></div><div class="item"><div class="label">Target Completion</div><div class="value">{{ $project->target_completion_date?->format('d F Y') ?? '-' }}</div></div><div class="item"><div class="label">Project Month</div><div class="value">{{ $project->project_month?->format('F Y') ?? '-' }}</div></div><div class="item"><div class="label">Location</div><div class="value">{{ $project->location ?: '-' }}</div></div><div class="item"><div class="label">Coordinates</div><div class="value">{{ data_get($project->latlong,'lat','-') }}, {{ data_get($project->latlong,'lng','-') }}</div></div></div><div class="progress"><div class="progress-head"><span class="label">Project Progress</span><span class="progress-value">{{ $project->progress }}%</span></div><div class="bar"><div class="fill" style="width:{{ $project->progress }}%"></div></div></div><div class="item wide"><div class="label">Description</div><div class="value">{{ $project->description ?: '-' }}</div></div><div class="item wide"><div class="label">Notes</div><div class="value">{{ $project->notes ?: '-' }}</div></div><div class="bottom"><a class="btn" href="{{ route('admin.projects.index') }}">Daftar Project</a><form class="delete-form" method="POST" action="{{ route('admin.projects.destroy',$project) }}">@csrf @method('DELETE')<button class="btn danger" type="submit">Hapus Project</button></form></div></div></div>
<script>document.querySelector('.delete-form')?.addEventListener('submit',function(e){e.preventDefault();Swal.fire({title:'Hapus project?',text:'Project ini akan dihapus permanen.',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, hapus',cancelButtonText:'Batal',confirmButtonColor:'#dc2626'}).then(r=>{if(r.isConfirmed)this.submit()})});@if(session('success'))Swal.fire({toast:true,position:'top-end',icon:'success',title:@json(session('success')),showConfirmButton:false,timer:2200,timerProgressBar:true});@endif</script>
</body></html>
