<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Project Detail — Tazaka Elektrik Teknologi</title><link rel="icon" type="image/png" href="https://tazaka.co.id/assets/logo-tazaka-PPqkEZXu.png"><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>*{box-sizing:border-box}body{margin:0;background:#0b1020;color:#eef2ff;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.wrap{max-width:950px;margin:auto;padding:32px}.card{background:#111827;border:1px solid #1f2937;border-radius:18px;padding:0;box-shadow:0 18px 50px #0003;overflow:hidden}.card-header{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:22px 24px;border-bottom:1px solid #1f2937}.card-title{font-size:20px;font-weight:850;margin:0}.muted{font-size:13px;color:#64748b}.card-body{padding:24px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.item{background:#0b1222;border:1px solid #1f2937;border-radius:12px;padding:15px}.label{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:.08em;font-weight:800}.value{font-size:15px;color:#e2e8f0;margin-top:6px}.value.rich{line-height:1.7}.value.rich p{margin:0 0 12px}.value.rich ul,.value.rich ol{margin:0 0 12px;padding-left:24px}.value.rich strong,.value.rich b{color:#fff}.value.rich a{color:#7dd3fc}.progress{margin:20px 0}.progress-head{display:flex;justify-content:space-between;margin-bottom:8px}.progress-value{font-size:22px;font-weight:800;color:#7dd3fc}.bar{height:9px;border-radius:99px;background:#1e293b;overflow:hidden}.fill{height:100%;background:#38bdf8;border-radius:99px}.wide{margin-top:12px}.card-footer{display:flex;justify-content:flex-end;gap:10px;padding:18px 24px;border-top:1px solid #1f2937;background:#0d1424}.footbar{display:flex;justify-content:flex-start;margin:10px 0 20px}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:10px;padding:11px 16px;background:#1e293b;color:#fff;cursor:pointer;font-weight:700;text-decoration:none}.btn.primary{background:#2563eb}.btn.danger{background:#7f1d1d}.delete-form{margin:0}@media(max-width:600px){.wrap{padding:18px}.grid{grid-template-columns:1fr}.card-footer{flex-direction:column}.card-footer .btn,.card-footer form{width:100%}.card-footer form .btn{width:100%}.footbar{margin-top:10px}.card-header{align-items:flex-start;flex-direction:column}}
</style></head>
<body><div class="wrap">
<x-admin-header />
<div class="card"><div class="card-header"><h1 class="card-title">Project Detail</h1><span class="muted">{{ $project->name }}</span></div><div class="card-body"><div class="grid"><div class="item"><div class="label">Project Name</div><div class="value">{{ $project->name }}</div></div><div class="item"><div class="label">Client</div><div class="value">{{ $project->client }}</div></div><div class="item"><div class="label">Project Type</div><div class="value">{{ str_replace('_',' ',ucfirst($project->project_type)) }}</div></div><div class="item"><div class="label">Progress</div><div class="value">{{ $project->progress }}%</div></div><div class="item"><div class="label">Target Completion</div><div class="value">{{ $project->target_completion_date?->format('d F Y') ?? '-' }}</div></div><div class="item"><div class="label">Project Month</div><div class="value">{{ $project->project_month?->format('F Y') ?? '-' }}</div></div><div class="item"><div class="label">Location</div><div class="value">{{ $project->location ?: '-' }}</div></div><div class="item"><div class="label">Coordinates</div><div class="value">{{ data_get($project->latlong,'lat','-') }}, {{ data_get($project->latlong,'lng','-') }}</div></div></div><div class="progress"><div class="progress-head"><span class="label">Project Progress</span><span class="progress-value">{{ $project->progress }}%</span></div><div class="bar"><div class="fill" style="width:{{ $project->progress }}%"></div></div></div><div class="item wide"><div class="label">Description</div><div class="value rich">{!! html_entity_decode($project->description ?: '-', ENT_QUOTES | ENT_HTML5, 'UTF-8') !!}</div></div><div class="item wide"><div class="label">Notes</div><div class="value rich">{!! html_entity_decode($project->notes ?: '-', ENT_QUOTES | ENT_HTML5, 'UTF-8') !!}</div></div></div><div class="card-footer"><a class="btn primary" href="{{ route('admin.projects.edit',$project) }}">Edit Project</a><form class="delete-form" method="POST" action="{{ route('admin.projects.destroy',$project) }}">@csrf @method('DELETE')<button class="btn danger" type="submit">Hapus Project</button></form></div></div>
<div class="footbar"><a class="btn" href="{{ route('admin.projects.index') }}">← Kembali ke Project</a></div>
<script>document.querySelector('.delete-form')?.addEventListener('submit',function(e){e.preventDefault();Swal.fire({title:'Hapus project?',text:'Project ini akan dihapus permanen.',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, hapus',cancelButtonText:'Batal',confirmButtonColor:'#dc2626'}).then(r=>{if(r.isConfirmed)this.submit()})});@if(session('success'))Swal.fire({toast:true,position:'top-end',icon:'success',title:@json(session('success')),showConfirmButton:false,timer:2200,timerProgressBar:true});@endif</script>
</body></html>
