<style>
.detail-backdrop{display:flex;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .28s ease,visibility .28s ease}.detail-backdrop.open{display:flex;opacity:1;visibility:visible;pointer-events:auto}.detail-backdrop .detail-modal{transform:translateY(18px) scale(.96);opacity:0;transition:transform .32s cubic-bezier(.22,1,.36,1),opacity .24s ease}.detail-backdrop.open .detail-modal{transform:translateY(0) scale(1);opacity:1}.detail-bar span{transition:width .75s cubic-bezier(.22,1,.36,1)}
.detail-media{width:min(48%,420px);margin:22px 0 0 auto}.detail-gallery{position:relative;border:1px solid #1e293b;border-radius:16px;overflow:hidden;background:#050a12;aspect-ratio:16/10;cursor:zoom-in}.detail-gallery img{width:100%;height:100%;display:block;object-fit:cover;transition:transform .35s ease}.detail-gallery:hover img{transform:scale(1.045)}.detail-gallery-empty{height:100%;display:flex;align-items:center;justify-content:center;color:#64748b;font-size:12px}.detail-gallery-nav{position:absolute;inset:0;display:flex;align-items:center;justify-content:space-between;padding:0 9px;pointer-events:none}.detail-gallery-nav button{pointer-events:auto;width:34px;height:34px;border:1px solid rgba(255,255,255,.18);border-radius:50%;background:rgba(2,6,23,.68);color:#fff;font-size:22px;line-height:1;cursor:pointer;backdrop-filter:blur(6px)}.detail-gallery-nav button:hover{background:rgba(15,23,42,.92)}.detail-gallery-count{position:absolute;right:10px;bottom:10px;padding:5px 8px;border-radius:999px;background:rgba(2,6,23,.72);color:#cbd5e1;font-size:10px}.detail-map-wrap{margin-top:12px;height:210px;border:1px solid #1e293b;border-radius:16px;overflow:hidden;background:#0a101b}.detail-map{width:100%;height:100%}.detail-lightbox{position:fixed;inset:0;z-index:5000;display:none;align-items:center;justify-content:center;padding:30px;background:rgba(0,0,0,.9);backdrop-filter:blur(8px)}.detail-lightbox.open{display:flex}.detail-lightbox img{max-width:94vw;max-height:88vh;object-fit:contain;border-radius:12px;box-shadow:0 30px 100px rgba(0,0,0,.65)}.detail-lightbox-close{position:absolute;top:18px;right:22px;width:42px;height:42px;border:1px solid #475569;border-radius:50%;background:#111827;color:#fff;font-size:26px;cursor:pointer}.detail-lightbox-nav{position:absolute;inset:0;display:flex;align-items:center;justify-content:space-between;padding:0 24px;pointer-events:none}.detail-lightbox-nav button{pointer-events:auto;width:46px;height:46px;border:1px solid #475569;border-radius:50%;background:rgba(15,23,42,.8);color:#fff;font-size:28px;cursor:pointer}@media(max-width:700px){.detail-media{width:100%;margin-left:0}.detail-map-wrap{height:190px}}
.progress-update-toast{position:fixed;right:26px;bottom:26px;z-index:3000;min-width:290px;max-width:380px;padding:14px 16px;border:1px solid rgba(56,189,248,.3);border-radius:15px;background:rgba(10,18,32,.94);box-shadow:0 18px 45px rgba(0,0,0,.42);backdrop-filter:blur(12px);transform:translateY(18px) scale(.97);opacity:0;pointer-events:none;transition:opacity .25s ease,transform .3s cubic-bezier(.22,1,.36,1)}.progress-update-toast.show{opacity:1;transform:translateY(0) scale(1)}.progress-update-toast.strong{border-color:rgba(250,204,21,.55);box-shadow:0 18px 50px rgba(250,204,21,.12),0 18px 45px rgba(0,0,0,.42)}.progress-update-toast-title{font-size:10px;letter-spacing:.13em;text-transform:uppercase;color:#7dd3fc;font-weight:800;margin-bottom:5px}.progress-update-toast.strong .progress-update-toast-title{color:#fde68a}.progress-update-toast-project{font-size:13px;color:#f8fafc;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.progress-update-toast-value{font-size:11px;color:#94a3b8;margin-top:4px}.progress-update-toast-value strong{color:#34d399;font-size:13px}.project.progress-pulse{animation:progressPulse .8s cubic-bezier(.22,1,.36,1)}.project.progress-pulse-strong{animation:progressPulseStrong 1.15s cubic-bezier(.22,1,.36,1)}@keyframes progressPulse{0%{box-shadow:0 16px 35px rgba(0,0,0,.25)}35%{box-shadow:0 0 0 3px rgba(56,189,248,.28),0 0 35px rgba(56,189,248,.24),0 20px 45px rgba(0,0,0,.35)}100%{box-shadow:0 16px 35px rgba(0,0,0,.25)}}@keyframes progressPulseStrong{0%{transform:scale(1);box-shadow:0 16px 35px rgba(0,0,0,.25)}25%{transform:scale(1.012);box-shadow:0 0 0 4px rgba(250,204,21,.3),0 0 55px rgba(250,204,21,.34),0 25px 55px rgba(0,0,0,.4)}60%{transform:scale(1.006);box-shadow:0 0 0 2px rgba(56,189,248,.18),0 0 35px rgba(56,189,248,.2),0 20px 45px rgba(0,0,0,.35)}100%{transform:scale(1);box-shadow:0 16px 35px rgba(0,0,0,.25)}}
@media(max-width:600px){.progress-update-toast{right:16px;left:16px;bottom:16px;min-width:0;max-width:none}}
</style>
<script>
(() => {
    const endpoint=@json(route('monitor.data'));
    let galleryImages=[]; let galleryIndex=0; let detailMap=null; let detailMarker=null; let toastTimer=null; let realtimeConnected=false; let refreshInFlight=false; let monitorSignature='';
    const progressGradient=p=>{p=Math.max(0,Math.min(100,Number(p)||0));if(p>=100)return'linear-gradient(90deg,#10b981,#34d399)';if(p>=80)return'linear-gradient(90deg,#22c55e,#84cc16)';if(p>=60)return'linear-gradient(90deg,#eab308,#facc15)';if(p>=30)return'linear-gradient(90deg,#f97316,#fbbf24)';return'linear-gradient(90deg,#ef4444,#fb7185)'};
    const animateValue=(element,target,duration=750,suffix='%')=>{if(!element)return;const start=Number(element.dataset.progressValue??element.textContent.replace(/[^0-9.-]/g,''))||0;const end=Math.max(0,Math.min(100,Number(target)||0));const started=performance.now();const ease=t=>1-Math.pow(1-t,3);const step=now=>{const t=Math.min(1,(now-started)/duration);const value=Math.round(start+(end-start)*ease(t));element.textContent=value+suffix;element.dataset.progressValue=String(value);if(t<1)requestAnimationFrame(step)};requestAnimationFrame(step)};
    const getToast=()=>{let el=document.getElementById('progressUpdateToast');if(el)return el;el=document.createElement('div');el.id='progressUpdateToast';el.className='progress-update-toast';el.innerHTML='<div class="progress-update-toast-title">Progress Updated</div><div class="progress-update-toast-project"></div><div class="progress-update-toast-value"></div>';document.body.appendChild(el);return el};
    const showProgressToast=(project,oldProgress,newProgress)=>{const el=getToast();const delta=newProgress-oldProgress;el.classList.toggle('strong',delta>10);el.querySelector('.progress-update-toast-project').textContent=project?.name||'Project';el.querySelector('.progress-update-toast-value').innerHTML=`${oldProgress}% <span style="color:#64748b">→</span> <strong>${newProgress}%</strong>`;clearTimeout(toastTimer);requestAnimationFrame(()=>el.classList.add('show'));toastTimer=setTimeout(()=>el.classList.remove('show'),delta>10?4200:3000)};
    const pulseProject=(card,significant=false)=>{if(!card)return;card.classList.remove('progress-pulse','progress-pulse-strong');void card.offsetWidth;card.classList.add(significant?'progress-pulse-strong':'progress-pulse');setTimeout(()=>card.classList.remove('progress-pulse','progress-pulse-strong'),significant?1200:850)};
    const animateProjectBars=(projects,previousProjects=null,showFeedback=false)=>{const previousById=new Map((previousProjects||[]).map(p=>[Number(p.id),p]));projects.forEach(p=>{const card=document.querySelector(`.project[data-project-id="${Number(p.id)}"]`);if(!card)return;const target=Math.max(0,Math.min(100,Number(p.progress)||0));const b=card.querySelector('.bar');const text=card.querySelector('.progress-label strong');if(b){b.style.background=progressGradient(target);if(showFeedback){b.style.width=target+'%'}else{b.style.transition='none';b.style.width=target+'%';requestAnimationFrame(()=>{b.style.transition='width .75s cubic-bezier(.22,1,.36,1)'})}}if(text){if(showFeedback)animateValue(text,target);else{text.textContent=target+'%';text.dataset.progressValue=String(target)}}if(showFeedback){const previous=previousById.get(Number(p.id));if(previous){const oldProgress=Math.max(0,Math.min(100,Number(previous.progress)||0));if(oldProgress!==target){const delta=target-oldProgress;pulseProject(card,delta>10);if(delta>0)showProgressToast(p,oldProgress,target)}}}})};
    const storageUrl=path=>{if(!path)return '';return '/storage/'+String(path).replace(/^\/+/, '').split('/').map(encodeURIComponent).join('/')};
    const ensureDetailExtras=()=>{const modal=document.querySelector('#projectDetail .detail-modal');if(!modal)return null;let media=modal.querySelector('.detail-media-grid');if(media)return media;media=document.createElement('div');media.className='detail-media-grid';media.innerHTML='<div class="detail-gallery" id="detailGallery"><div class="detail-gallery-empty">Belum ada image project</div></div><div class="detail-location-map"><div id="detailProjectMap" class="detail-map"></div></div>';const hint=modal.querySelector('.detail-hint');if(hint)modal.insertBefore(media,hint);else modal.appendChild(media);let lightbox=document.getElementById('detailLightbox');if(!lightbox){lightbox=document.createElement('div');lightbox.id='detailLightbox';lightbox.className='detail-lightbox';lightbox.innerHTML='<button class="detail-lightbox-close" type="button" aria-label="Close">×</button><div class="detail-lightbox-nav"><button type="button" data-dir="-1">‹</button><button type="button" data-dir="1">›</button></div><img id="detailLightboxImage" alt="Project image">';document.body.appendChild(lightbox);lightbox.querySelector('.detail-lightbox-close').onclick=()=>lightbox.classList.remove('open');lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.classList.remove('open')});lightbox.querySelectorAll('[data-dir]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();changeGallery(Number(btn.dataset.dir),true)});document.addEventListener('keydown',e=>{if(!lightbox.classList.contains('open'))return;if(e.key==='Escape')lightbox.classList.remove('open');if(e.key==='ArrowLeft')changeGallery(-1,true);if(e.key==='ArrowRight')changeGallery(1,true)})}return media};
    const changeGallery=(delta,full=false)=>{if(!galleryImages.length)return;galleryIndex=(galleryIndex+delta+galleryImages.length)%galleryImages.length;renderGallery(full)};
    const renderGallery=(full=false)=>{const gallery=document.getElementById('detailGallery');if(!gallery)return;if(!galleryImages.length){gallery.innerHTML='<div class="detail-gallery-empty">Belum ada image project</div>';return}const url=storageUrl(galleryImages[galleryIndex]?.path);gallery.innerHTML=`<img src="${url}" alt="Project image" loading="lazy"><div class="detail-gallery-nav"><button type="button" data-dir="-1">‹</button><button type="button" data-dir="1">›</button></div><div class="detail-gallery-count">${galleryIndex+1} / ${galleryImages.length}</div>`;gallery.querySelectorAll('[data-dir]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();changeGallery(Number(btn.dataset.dir))});gallery.querySelector('img').onclick=()=>{const lb=document.getElementById('detailLightbox');const image=document.getElementById('detailLightboxImage');if(lb&&image){image.src=url;lb.classList.add('open')}}};
    const renderDetailMap=project=>{const el=document.getElementById('detailProjectMap');if(!el||typeof L==='undefined')return;const lat=Number(project?.latlong?.lat);const lng=Number(project?.latlong?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)){if(detailMap){detailMap.remove();detailMap=null;detailMarker=null}el.innerHTML='<div style="height:100%;display:flex;align-items:center;justify-content:center;color:#64748b;font-size:12px">Lokasi project belum tersedia</div>';return}if(!detailMap){el.innerHTML='';detailMap=L.map(el,{zoomControl:true,scrollWheelZoom:false,attributionControl:true}).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(detailMap);detailMarker=L.marker([lat,lng]).addTo(detailMap)}else{detailMap.setView([lat,lng],15);if(detailMarker)detailMarker.setLatLng([lat,lng]);else detailMarker=L.marker([lat,lng]).addTo(detailMap)}detailMarker.bindPopup(`<strong>${String(project.name||'Project').replace(/[<>&]/g,'')}</strong>`).openPopup();setTimeout(()=>detailMap.invalidateSize(),80)};
    const loadProject=async id=>{const project=(window.__monitorProjects||[]).find(p=>Number(p.id)===Number(id));if(!project)return;ensureDetailExtras();galleryImages=Array.isArray(project.images)?project.images.slice().sort((a,b)=>Number(a.sort_order||0)-Number(b.sort_order||0)):[];galleryIndex=0;renderGallery();renderDetailMap(project);const progress=Math.max(0,Math.min(100,Number(project.progress)||0));const progressBar=document.getElementById('detailProgressBar');const progressText=document.getElementById('detailProgressText');if(progressBar)progressBar.style.width=progress+'%';if(progressText){progressText.textContent=progress+'%';progressText.dataset.progressValue=String(progress)}};
    const syncOpenDetail=()=>{const modal=document.getElementById('projectDetail');if(!modal?.classList.contains('open'))return;const id=Number(modal.dataset.projectId||0);if(id)loadProject(id)};
    document.addEventListener('click',e=>{if(e.target.closest('.project'))setTimeout(syncOpenDetail,0)});
    const detailObserver=new MutationObserver(syncOpenDetail);document.addEventListener('DOMContentLoaded',()=>{const modal=document.getElementById('projectDetail');if(modal)detailObserver.observe(modal,{attributes:true,attributeFilter:['class','data-project-id']})});
    window.__monitorProjects=window.__monitorProjects||[];
    const refreshMonitor=async({feedback=false,force=false}={})=>{if(refreshInFlight)return;refreshInFlight=true;try{const previousProjects=[...(window.__monitorProjects||[])];const r=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const d=await r.json();const nextProjects=d.projects||[];if(Array.isArray(d.monthly_project_counts))monthlyProjectCounts=d.monthly_project_counts;const nextSignature=JSON.stringify(nextProjects.map(p=>({id:p.id,updated_at:p.updated_at,progress:p.progress,sort_order:p.sort_order,images:p.images})));if(!force&&nextSignature===monitorSignature)return;monitorSignature=nextSignature;window.__monitorProjects=nextProjects;if(typeof render==='function')render(nextProjects,d.summary||null);if(typeof renderMap==='function')renderMap(nextProjects);animateProjectBars(nextProjects,previousProjects,feedback);syncOpenDetail()}catch(e){console.error('Monitor refresh gagal:',e)}finally{refreshInFlight=false}};
    if(typeof Pusher==='undefined'){console.error('Pusher.js tidak tersedia. Realtime tidak dapat dijalankan.')}else{
        const pusher=new Pusher(@json(env('REVERB_APP_KEY')), {cluster:'mt1',wsHost:@json(env('REVERB_HOST','127.0.0.1')),wsPort:Number(@json(env('REVERB_PORT',8085))),wssPort:Number(@json(env('REVERB_PORT',8085))),forceTLS:@json(env('REVERB_SCHEME','http'))==='https',enabledTransports:['ws','wss'],disableStats:true});
        const channel=pusher.subscribe('monitor');
        channel.bind('project.updated',payload=>{console.info('Reverb project.updated',payload);refreshMonitor({feedback:true,force:true})});
        pusher.connection.bind('connected',()=>{realtimeConnected=true;console.info('Monitor REALTIME terhubung ke Reverb.')});
        pusher.connection.bind('disconnected',()=>{realtimeConnected=false;console.warn('Reverb terputus.')});
        pusher.connection.bind('error',e=>{realtimeConnected=false;console.error('Koneksi Reverb gagal:',e)});
    }
    refreshMonitor({feedback:false,force:true});
})();
</script>
