<style>
.detail-backdrop{display:flex;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .28s ease,visibility .28s ease}.detail-backdrop.open{display:flex;opacity:1;visibility:visible;pointer-events:auto}.detail-backdrop .detail-modal{transform:translateY(18px) scale(.96);opacity:0;transition:transform .32s cubic-bezier(.22,1,.36,1),opacity .24s ease}.detail-backdrop.open .detail-modal{transform:translateY(0) scale(1);opacity:1}.detail-bar span{transition:width .75s cubic-bezier(.22,1,.36,1)}.project{animation:projectEnter .45s cubic-bezier(.22,1,.36,1) both}.project:nth-child(2){animation-delay:.04s}.project:nth-child(3){animation-delay:.08s}.project:nth-child(4){animation-delay:.12s}.project:nth-child(5){animation-delay:.16s}.project:nth-child(6){animation-delay:.20s}.project:nth-child(7){animation-delay:.24s}.project:nth-child(8){animation-delay:.28s}@keyframes projectEnter{from{opacity:0;transform:translateY(12px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}
.progress-update-toast{position:fixed;right:26px;bottom:26px;z-index:3000;min-width:290px;max-width:380px;padding:14px 16px;border:1px solid rgba(56,189,248,.3);border-radius:15px;background:rgba(10,18,32,.94);box-shadow:0 18px 45px rgba(0,0,0,.42);backdrop-filter:blur(12px);transform:translateY(18px) scale(.97);opacity:0;pointer-events:none;transition:opacity .25s ease,transform .3s cubic-bezier(.22,1,.36,1)}.progress-update-toast.show{opacity:1;transform:translateY(0) scale(1)}.progress-update-toast.strong{border-color:rgba(250,204,21,.55);box-shadow:0 18px 50px rgba(250,204,21,.12),0 18px 45px rgba(0,0,0,.42)}.progress-update-toast-title{font-size:10px;letter-spacing:.13em;text-transform:uppercase;color:#7dd3fc;font-weight:800;margin-bottom:5px}.progress-update-toast.strong .progress-update-toast-title{color:#fde68a}.progress-update-toast-project{font-size:13px;color:#f8fafc;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.progress-update-toast-value{font-size:11px;color:#94a3b8;margin-top:4px}.progress-update-toast-value strong{color:#34d399;font-size:13px}.project.progress-pulse{animation:progressPulse .8s cubic-bezier(.22,1,.36,1)}.project.progress-pulse-strong{animation:progressPulseStrong 1.15s cubic-bezier(.22,1,.36,1)}@keyframes progressPulse{0%{box-shadow:0 16px 35px rgba(0,0,0,.25)}35%{box-shadow:0 0 0 3px rgba(56,189,248,.28),0 0 35px rgba(56,189,248,.24),0 20px 45px rgba(0,0,0,.35)}100%{box-shadow:0 16px 35px rgba(0,0,0,.25)}}@keyframes progressPulseStrong{0%{transform:scale(1);box-shadow:0 16px 35px rgba(0,0,0,.25)}25%{transform:scale(1.012);box-shadow:0 0 0 4px rgba(250,204,21,.3),0 0 55px rgba(250,204,21,.34),0 25px 55px rgba(0,0,0,.4)}60%{transform:scale(1.006);box-shadow:0 0 0 2px rgba(56,189,248,.18),0 0 35px rgba(56,189,248,.2),0 20px 45px rgba(0,0,0,.35)}100%{transform:scale(1);box-shadow:0 16px 35px rgba(0,0,0,.25)}}
@media(max-width:600px){.progress-update-toast{right:16px;left:16px;bottom:16px;min-width:0;max-width:none}}
</style>
<script>
(() => {
    const endpoint=@json(route('monitor.data'));
    let galleryImages=[]; let galleryIndex=0; let detailMap=null; let detailMarker=null; let realtimeConnected=false; let refreshTimer=null; let toastTimer=null; let refreshInFlight=false; let monitorSignature='';
    const progressGradient=p=>{p=Math.max(0,Math.min(100,Number(p)||0));if(p>=100)return'linear-gradient(90deg,#10b981,#34d399)';if(p>=80)return'linear-gradient(90deg,#22c55e,#84cc16)';if(p>=60)return'linear-gradient(90deg,#eab308,#facc15)';if(p>=30)return'linear-gradient(90deg,#f97316,#fbbf24)';return'linear-gradient(90deg,#ef4444,#fb7185)'};
    const animateValue=(element,target,duration=750,suffix='%')=>{if(!element)return;const start=Number(element.dataset.progressValue??element.textContent.replace(/[^0-9.-]/g,''))||0;const end=Math.max(0,Math.min(100,Number(target)||0));const started=performance.now();const ease=t=>1-Math.pow(1-t,3);const step=now=>{const t=Math.min(1,(now-started)/duration);const value=Math.round(start+(end-start)*ease(t));element.textContent=value+suffix;element.dataset.progressValue=String(value);if(t<1)requestAnimationFrame(step)};requestAnimationFrame(step)};
    const getToast=()=>{let el=document.getElementById('progressUpdateToast');if(el)return el;el=document.createElement('div');el.id='progressUpdateToast';el.className='progress-update-toast';el.innerHTML='<div class="progress-update-toast-title">Progress Updated</div><div class="progress-update-toast-project"></div><div class="progress-update-toast-value"></div>';document.body.appendChild(el);return el};
    const showProgressToast=(project,oldProgress,newProgress)=>{const el=getToast();const delta=newProgress-oldProgress;el.classList.toggle('strong',delta>10);el.querySelector('.progress-update-toast-project').textContent=project?.name||'Project';el.querySelector('.progress-update-toast-value').innerHTML=`${oldProgress}% <span style="color:#64748b">→</span> <strong>${newProgress}%</strong>`;clearTimeout(toastTimer);requestAnimationFrame(()=>el.classList.add('show'));toastTimer=setTimeout(()=>el.classList.remove('show'),delta>10?4200:3000)};
    const pulseProject=(card,significant=false)=>{if(!card)return;card.classList.remove('progress-pulse','progress-pulse-strong');void card.offsetWidth;card.classList.add(significant?'progress-pulse-strong':'progress-pulse');setTimeout(()=>card.classList.remove('progress-pulse','progress-pulse-strong'),significant?1200:850)};
    const animateProjectBars=(projects,previousProjects=null,showFeedback=false)=>{const previousById=new Map((previousProjects||[]).map(p=>[Number(p.id),p]));projects.forEach(p=>{const card=document.querySelector(`.project[data-project-id="${Number(p.id)}"]`);if(!card)return;const target=Math.max(0,Math.min(100,Number(p.progress)||0));const b=card.querySelector('.bar');const text=card.querySelector('.progress-label strong');if(b){b.style.background=progressGradient(target);b.style.width=target+'%'}if(text)animateValue(text,target);if(showFeedback){const previous=previousById.get(Number(p.id));if(previous){const oldProgress=Math.max(0,Math.min(100,Number(previous.progress)||0));if(oldProgress!==target){const delta=target-oldProgress;pulseProject(card,delta>10);if(delta>0)showProgressToast(p,oldProgress,target)}}}})};
    const loadProject=async id=>{let project=(window.__monitorProjects||[]).find(p=>Number(p.id)===Number(id));if(!project){try{const r=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json();window.__monitorProjects=d.projects||[];project=window.__monitorProjects.find(p=>Number(p.id)===Number(id))}catch(e){console.error('Project detail gagal dimuat:',e)}}if(!project)return;const progress=Math.max(0,Math.min(100,Number(project.progress)||0));const progressBar=document.getElementById('detailProgressBar');const progressText=document.getElementById('detailProgressText');if(progressBar){progressBar.style.width=progress+'%'}if(progressText)animateValue(progressText,progress)};
    const buildDetailLayoutAndSync=()=>{const modal=document.getElementById('projectDetail');if(!modal?.classList.contains('open'))return;const id=Number(modal.dataset.projectId||0);if(id)loadProject(id)};
    window.__monitorProjects=window.__monitorProjects||[];
    const refreshMonitor=async({feedback=false,force=false}={})=>{if(refreshInFlight)return;refreshInFlight=true;try{const previousProjects=[...(window.__monitorProjects||[])];const r=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const d=await r.json();const nextProjects=d.projects||[];const nextSignature=JSON.stringify(nextProjects.map(p=>({id:p.id,updated_at:p.updated_at,progress:p.progress,sort_order:p.sort_order,images:p.images})));if(!force&&nextSignature===monitorSignature)return;monitorSignature=nextSignature;window.__monitorProjects=nextProjects;if(typeof render==='function')render(nextProjects,d.summary||null);if(typeof renderMap==='function')renderMap(nextProjects);animateProjectBars(nextProjects,previousProjects,feedback);buildDetailLayoutAndSync()}catch(e){console.error('Monitor refresh gagal:',e)}finally{refreshInFlight=false}};
    if(typeof Pusher==='undefined'){console.error('Pusher.js tidak tersedia. Fallback polling aktif.')}else{
        const pusher=new Pusher(@json(env('REVERB_APP_KEY')), {cluster:'mt1',wsHost:@json(env('REVERB_HOST','127.0.0.1')),wsPort:Number(@json(env('REVERB_PORT',8085))),wssPort:Number(@json(env('REVERB_PORT',8085))),forceTLS:@json(env('REVERB_SCHEME','http'))==='https',enabledTransports:['ws','wss'],disableStats:true});
        const channel=pusher.subscribe('monitor');
        channel.bind('project.updated',()=>refreshMonitor({feedback:true,force:true}));
        pusher.connection.bind('connected',()=>{realtimeConnected=true;console.info('Monitor realtime terhubung ke Reverb.')});
        pusher.connection.bind('disconnected',()=>{realtimeConnected=false;console.warn('Reverb terputus. Polling fallback aktif.')});
        pusher.connection.bind('error',e=>{realtimeConnected=false;console.error('Koneksi Reverb gagal:',e)});
    }
    refreshMonitor({feedback:false,force:true});
    refreshTimer=setInterval(()=>{if(!realtimeConnected)refreshMonitor({feedback:false})},2000);
})();
</script>