<style>
.detail-backdrop{display:flex;opacity:0;visibility:hidden;pointer-events:none;transition:opacity .28s ease,visibility .28s ease}.detail-backdrop.open{display:flex;opacity:1;visibility:visible;pointer-events:auto}.detail-backdrop .detail-modal{transform:translateY(18px) scale(.96);opacity:0;transition:transform .32s cubic-bezier(.22,1,.36,1),opacity .24s ease}.detail-backdrop.open .detail-modal{transform:translateY(0) scale(1);opacity:1}.detail-bar span{transition:width .75s cubic-bezier(.22,1,.36,1)}.project{animation:projectEnter .45s cubic-bezier(.22,1,.36,1) both}.project:nth-child(2){animation-delay:.04s}.project:nth-child(3){animation-delay:.08s}.project:nth-child(4){animation-delay:.12s}.project:nth-child(5){animation-delay:.16s}.project:nth-child(6){animation-delay:.20s}.project:nth-child(7){animation-delay:.24s}.project:nth-child(8){animation-delay:.28s}@keyframes projectEnter{from{opacity:0;transform:translateY(12px) scale(.985)}to{opacity:1;transform:translateY(0) scale(1)}}
</style>
<script>
(() => {
    const endpoint=@json(route('monitor.data'));
    let galleryImages=[]; let galleryIndex=0; let detailMap=null; let detailMarker=null; let realtimeConnected=false; let refreshTimer=null;
    const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
    const imageUrl=image=>{const p=String(image?.path||'').trim();if(!p)return '';if(p.startsWith('http://')||p.startsWith('https://'))return p;return '/storage/'+p.replace(/^\/+/, '')};
    const progressGradient=p=>{p=Math.max(0,Math.min(100,Number(p)||0));if(p>=100)return'linear-gradient(90deg,#10b981,#34d399)';if(p>=80)return'linear-gradient(90deg,#22c55e,#84cc16)';if(p>=60)return'linear-gradient(90deg,#eab308,#facc15)';if(p>=30)return'linear-gradient(90deg,#f97316,#fbbf24)';return'linear-gradient(90deg,#ef4444,#fb7185)'};
    const animateValue=(element,target,duration=750,suffix='%')=>{if(!element)return;const start=Number(element.dataset.progressValue??element.textContent.replace(/[^0-9.-]/g,''))||0;const end=Math.max(0,Math.min(100,Number(target)||0));const started=performance.now();const ease=t=>1-Math.pow(1-t,3);const step=now=>{const t=Math.min(1,(now-started)/duration);const value=Math.round(start+(end-start)*ease(t));element.textContent=value+suffix;element.dataset.progressValue=String(value);if(t<1)requestAnimationFrame(step)};requestAnimationFrame(step)};
    const animateProjectBars=projects=>{projects.forEach(p=>{const card=document.querySelector(`.project[data-project-id="${Number(p.id)}"]`);if(!card)return;const target=Math.max(0,Math.min(100,Number(p.progress)||0));const b=card.querySelector('.bar');const text=card.querySelector('.progress-label strong');if(b){b.style.background=progressGradient(target);b.style.width='0%';requestAnimationFrame(()=>requestAnimationFrame(()=>{b.style.width=target+'%'}))}if(text)animateValue(text,target)})};
    const buildDetailLayout=()=>{};
    const loadProject=async id=>{let project=(window.__monitorProjects||[]).find(p=>Number(p.id)===Number(id));if(!project){try{const r=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});const d=await r.json();window.__monitorProjects=d.projects||[];project=window.__monitorProjects.find(p=>Number(p.id)===Number(id))}catch(e){console.error('Project detail gagal dimuat:',e)}}if(!project)return;const progress=Math.max(0,Math.min(100,Number(project.progress)||0));const progressBar=document.getElementById('detailProgressBar');const progressText=document.getElementById('detailProgressText');if(progressBar){progressBar.style.width='0%';requestAnimationFrame(()=>requestAnimationFrame(()=>{progressBar.style.width=progress+'%'}))}if(progressText)animateValue(progressText,progress)};
    const buildDetailLayoutAndSync=()=>{const modal=document.getElementById('projectDetail');if(!modal?.classList.contains('open'))return;const id=Number(modal.dataset.projectId||0);if(id)loadProject(id)};
    window.__monitorProjects=window.__monitorProjects||[];
    const refreshMonitor=async()=>{try{const r=await fetch(endpoint,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)return;const d=await r.json();window.__monitorProjects=d.projects||[];if(typeof render==='function')render(d.projects||[],d.summary||null);if(typeof renderMap==='function')renderMap(d.projects||[]);animateProjectBars(d.projects||[]);buildDetailLayoutAndSync()}catch(e){console.error('Monitor refresh gagal:',e)}};
    const pusher=new Pusher(@json(env('REVERB_APP_KEY')), {cluster:'mt1',wsHost:@json(env('REVERB_HOST','127.0.0.1')),wsPort:Number(@json(env('REVERB_PORT',8085))),wssPort:Number(@json(env('REVERB_PORT',8085))),forceTLS:@json(env('REVERB_SCHEME','http'))==='https',enabledTransports:['ws','wss'],disableStats:true});
    const channel=pusher.subscribe('monitor');channel.bind('project.updated',refreshMonitor);pusher.connection.bind('connected',()=>{realtimeConnected=true;console.info('Monitor realtime terhubung ke Reverb.');});pusher.connection.bind('disconnected',()=>{realtimeConnected=false});pusher.connection.bind('error',e=>console.error('Koneksi Reverb gagal:',e));
    refreshTimer=setInterval(()=>{if(!realtimeConnected)refreshMonitor()},5000);
})();
</script>